export interface Reference {
  studio: string;
  eventName: string;
  year: number;
  item: string;
  description?: string;
}

export interface Vendor {
  id: string;
  name: string;
  location: string;
  description: string;
  website?: string;
  orderUrl: string;
  productTypes: string[];
  minOrderQty: number;
  unitPriceRange: { min: number; max: number };
  references: Reference[];
  tags: string[];
  reorderCount: number;
}

export const PRODUCT_CATEGORIES = [
  "전체",
  "짐색",
  "에코백",
  "토트백",
  "티셔츠",
  "후드티",
  "쉬폰 천 인쇄",
  "반다나",
  "포스터",
  "리소그래프",
  "스티커",
  "배지",
  "금속배지",
  "핀배지",
  "아크릴 키링",
  "렌티큘러 엽서",
  "텀블러",
  "모자",
  "양말",
  "노트",
  "랜야드",
  "차음료 패키지",
];

export const vendors: Vendor[] = [
  // ─── 에코백 / 짐색 / 토트백 ───────────────────────────────
  {
    id: "1",
    name: "에코코",
    location: "서울 용산구 (공장: 경기 김포)",
    description: "친환경 에코백·짐색·파우치 전문 제조 공장. 자체 실크스크린 인쇄 공정 보유, 친환경 인증 원단 직접 조달.",
    website: "https://ecoco.co.kr",
    orderUrl: "https://ecoco.co.kr/board/estimate/1/",
    productTypes: ["에코백", "짐색", "파우치", "토트백"],
    minOrderQty: 50,
    unitPriceRange: { min: 3500, max: 15000 },
    reorderCount: 28,
    references: [
      { studio: "Noname Press", eventName: "전주국제영화제", year: 2023, item: "짐색", description: "조리개백(짐색) 500개, 내추럴 면 소재 단면 실크스크린." },
      { studio: "Studio Maum", eventName: "서울재즈페스티벌", year: 2023, item: "에코백", description: "면 에코백 1,000개, 양면 2도 인쇄." },
      { studio: "Ordinary People", eventName: "언리미티드 에디션", year: 2022, item: "토트백", description: "캔버스 토트백 600개." },
    ],
    tags: ["친환경 인증", "실크스크린", "자체 공장", "소량 MOQ"],
  },
  {
    id: "2",
    name: "에코플로우",
    location: "인천 서구 청라",
    description: "에코백·토트백 전문 제조 공장. 디지털·스크린·전사 인쇄 모두 가능. 무료 시안 제공, 기업 맞춤 브랜딩 특화.",
    website: "https://eco-flow.co.kr",
    orderUrl: "https://eco-flow.co.kr",
    productTypes: ["에코백", "토트백", "파우치"],
    minOrderQty: 30,
    unitPriceRange: { min: 3000, max: 12000 },
    reorderCount: 14,
    references: [
      { studio: "Graphics Seoul", eventName: "부산국제영화제 (BIFF)", year: 2023, item: "에코백", description: "면 에코백 800개, 디지털 전사 인쇄." },
      { studio: "Studio Paikku", eventName: "서울아트북페어", year: 2022, item: "토트백", description: "캔버스 토트백 400개." },
    ],
    tags: ["무료 시안", "디지털 전사", "소량 가능", "기업 납품"],
  },

  // ─── 티셔츠 / 후드티 / 맨투맨 ────────────────────────────
  {
    id: "3",
    name: "레드프린팅 앤 프레스",
    location: "서울 성동구 성수동",
    description: "스티커·의류·패브릭·대형 출력까지 전 품목 커버. 오전 11시 주문 시 당일 출발 가능. 성수동 픽업 지원.",
    website: "https://www.redprinting.co.kr",
    orderUrl: "https://www.redprinting.co.kr/ko",
    productTypes: ["티셔츠", "에코백", "스티커", "포스터", "배지", "쉬폰 천 인쇄"],
    minOrderQty: 1,
    unitPriceRange: { min: 500, max: 35000 },
    reorderCount: 47,
    references: [
      { studio: "Graphics Seoul", eventName: "현대카드 뮤직 라이브러리", year: 2024, item: "티셔츠", description: "한정판 티셔츠 300장, 4도 인쇄." },
      { studio: "Noname Press", eventName: "서울국제도서전", year: 2023, item: "스티커", description: "다이컷 스티커 세트 2,000장." },
      { studio: "Studio Paikku", eventName: "서울아트북페어", year: 2023, item: "포스터", description: "A2 포스터 500장, 무광 코팅." },
    ],
    tags: ["당일 출발", "1개부터", "전 품목", "성수 픽업"],
  },
  {
    id: "4",
    name: "탑앤탑",
    location: "전국 (온라인)",
    description: "단체복 제작 20년 경력. 티셔츠·후드티·맨투맨·점퍼 전 품목. 6,000개 이상 상품, 1장부터 주문 가능.",
    website: "https://www.topntop.co.kr",
    orderUrl: "https://www.topntop.co.kr/",
    productTypes: ["티셔츠", "후드티", "맨투맨", "점퍼"],
    minOrderQty: 1,
    unitPriceRange: { min: 6000, max: 45000 },
    reorderCount: 36,
    references: [
      { studio: "Studio Paikku", eventName: "인디 뮤직 페스티벌", year: 2023, item: "후드티", description: "아티스트 콜라보 후드집업 150장." },
      { studio: "Ordinary People", eventName: "현대카드 슈퍼콘서트", year: 2024, item: "티셔츠", description: "스태프 단체티 200장." },
    ],
    tags: ["20년 경력", "1장부터", "6,000개 상품", "단체복 전문"],
  },
  {
    id: "5",
    name: "커스텀존",
    location: "전국 (온라인)",
    description: "세탁에 강한 인쇄 방식 특화. 티셔츠·후드·에코백 직접 제작 시스템으로 품질 일관성 높음.",
    website: "https://www.customzone.co.kr",
    orderUrl: "https://www.customzone.co.kr/",
    productTypes: ["티셔츠", "후드티", "에코백"],
    minOrderQty: 1,
    unitPriceRange: { min: 7000, max: 30000 },
    reorderCount: 22,
    references: [
      { studio: "Noname Press", eventName: "전주국제영화제", year: 2022, item: "티셔츠", description: "스태프용 반팔 150장." },
      { studio: "Graphics Seoul", eventName: "서울재즈페스티벌", year: 2023, item: "에코백", description: "행사 기념 에코백 500개." },
    ],
    tags: ["세탁 강한 인쇄", "직접 제작", "빠른 납기"],
  },
  {
    id: "6",
    name: "우리티",
    location: "서울 송파구",
    description: "(주)인비즈 운영. 반팔티 5,900원~, 맨투맨 12,900원~, 후드 17,900원~. 소량·단체 모두 지원.",
    website: "https://www.wooritee.com",
    orderUrl: "https://www.wooritee.com",
    productTypes: ["티셔츠", "맨투맨", "후드티", "에코백", "모자"],
    minOrderQty: 1,
    unitPriceRange: { min: 5900, max: 30000 },
    reorderCount: 19,
    references: [
      { studio: "Studio Maum", eventName: "서울국제도서전", year: 2024, item: "티셔츠", description: "스태프 반팔티 100장." },
      { studio: "Ordinary People", eventName: "서울재즈페스티벌", year: 2023, item: "맨투맨", description: "행사 스태프 맨투맨 80장." },
    ],
    tags: ["1장부터", "가성비", "송파 직접 픽업", "다품목"],
  },
  {
    id: "7",
    name: "무지싸게",
    location: "대구 수성구 신매동",
    description: "대구 공장 직영, 가성비 단체복 특화. 티셔츠 7,900원~, 맨투맨 14,900원~, 후드 28,900원~.",
    website: "https://mujissage.co.kr",
    orderUrl: "https://mujissage.co.kr",
    productTypes: ["티셔츠", "맨투맨", "후드티"],
    minOrderQty: 1,
    unitPriceRange: { min: 7900, max: 35000 },
    reorderCount: 15,
    references: [
      { studio: "Studio Paikku", eventName: "인디 뮤직 페스티벌", year: 2024, item: "티셔츠", description: "공연 기념 반팔티 200장." },
    ],
    tags: ["공장 직영", "가성비", "대구 소재", "대량 할인"],
  },
  {
    id: "8",
    name: "티프린스",
    location: "서울 강남구",
    description: "고퀄리티 단체복·단체티 전문. 기본 티셔츠 6,000원~. 바람막이·에코백·텀블러 등 다품목 병행.",
    website: "https://www.teeprince.com",
    orderUrl: "https://www.teeprince.com",
    productTypes: ["티셔츠", "후드티", "에코백", "텀블러"],
    minOrderQty: 1,
    unitPriceRange: { min: 6000, max: 40000 },
    reorderCount: 18,
    references: [
      { studio: "Graphics Seoul", eventName: "언리미티드 에디션", year: 2023, item: "티셔츠", description: "행사 스탭 티셔츠 120장." },
    ],
    tags: ["강남 소재", "고퀄리티", "다품목"],
  },
  {
    id: "9",
    name: "마플",
    location: "서울 강남구",
    description: "200만 고객 선택 커스텀 굿즈 No.1 플랫폼. 의류·에코백·머그·폰케이스 1개부터 주문 후 판매 연동 가능.",
    website: "https://www.marpple.com",
    orderUrl: "https://www.marpple.com/kr/",
    productTypes: ["티셔츠", "에코백", "후드티", "텀블러", "모자"],
    minOrderQty: 1,
    unitPriceRange: { min: 8000, max: 50000 },
    reorderCount: 61,
    references: [
      { studio: "Ordinary People", eventName: "카카오프렌즈 팝업스토어", year: 2024, item: "티셔츠", description: "팝업 한정 티셔츠 POD 운영." },
      { studio: "Studio Maum", eventName: "서울아트북페어", year: 2023, item: "에코백", description: "아티스트 에코백 소량 200개." },
    ],
    tags: ["POD 지원", "1개부터", "판매 연동", "12년 업력"],
  },

  // ─── 리소그래프 ────────────────────────────────────────────
  {
    id: "10",
    name: "코우너스 (Corners)",
    location: "서울",
    description: "2012년 설립. 리소그래피 인쇄소+독립출판사 운영. A2·A3 인쇄, 13가지 별색. 이메일 견적.",
    website: "https://corners.kr",
    orderUrl: "https://corners.kr/printing/risograph/about/",
    productTypes: ["리소그래프", "포스터", "엽서"],
    minOrderQty: 20,
    unitPriceRange: { min: 1500, max: 10000 },
    reorderCount: 21,
    references: [
      { studio: "Noname Press", eventName: "서울아트북페어", year: 2023, item: "리소그래프 포스터", description: "A3 리소 2도 포스터 300부." },
      { studio: "Studio Maum", eventName: "전주국제영화제", year: 2024, item: "리소그래프 포스터", description: "A2 3도 포스터 200부." },
    ],
    tags: ["2012년 설립", "A2 지원", "13가지 별색", "독립출판"],
  },
  {
    id: "11",
    name: "피융 (PIOONG)",
    location: "서울",
    description: "2도 리소그래프 인쇄. 형광 핑크·민트 등 14가지 별색, 친환경 소이 잉크. A3 최소 20장. 이메일 주문.",
    website: "https://pioong.com",
    orderUrl: "https://pioong.com/PRINT",
    productTypes: ["리소그래프", "포스터", "엽서"],
    minOrderQty: 20,
    unitPriceRange: { min: 1000, max: 8000 },
    reorderCount: 16,
    references: [
      { studio: "Graphics Seoul", eventName: "부산국제영화제 (BIFF)", year: 2024, item: "리소그래프 포스터", description: "A3 형광 2도 150부." },
      { studio: "Studio Paikku", eventName: "인디 뮤직 페스티벌", year: 2023, item: "엽서", description: "리소 엽서 100장, 3도 인쇄." },
    ],
    tags: ["소이 잉크", "형광 별색", "14가지 색상", "친환경"],
  },
  {
    id: "12",
    name: "소생공단 (페이퍼룸)",
    location: "제주시 조천읍",
    description: "제주 소재 리소그래프 스튜디오. POD 배송 서비스 운영. Etsy 글로벌 판매도 병행하는 독립 인쇄소.",
    website: "https://soseng.net",
    orderUrl: "https://soseng.net/shop/",
    productTypes: ["리소그래프", "포스터", "엽서"],
    minOrderQty: 10,
    unitPriceRange: { min: 1000, max: 7000 },
    reorderCount: 8,
    references: [
      { studio: "Studio Paikku", eventName: "언리미티드 에디션", year: 2023, item: "리소그래프 포스터", description: "A4 리소 포스터 80부." },
    ],
    tags: ["제주 소재", "POD 가능", "글로벌 배송", "독립 인쇄소"],
  },

  // ─── 스티커 / 포스터 / 엽서 ───────────────────────────────
  {
    id: "13",
    name: "오프린트미",
    location: "전국 (온라인)",
    description: "1장부터 가능한 온라인 인쇄 플랫폼. 스티커·포스터·명함·현수막 셀프 업로드 즉시 주문. 다양한 재질 선택.",
    website: "https://www.ohprint.me",
    orderUrl: "https://www.ohprint.me/store/sticker/overview",
    productTypes: ["스티커", "포스터", "엽서"],
    minOrderQty: 1,
    unitPriceRange: { min: 300, max: 8000 },
    reorderCount: 55,
    references: [
      { studio: "Noname Press", eventName: "전주국제영화제", year: 2022, item: "스티커", description: "포장 씰 다이컷 스티커 3,000장." },
      { studio: "Studio Maum", eventName: "서울국제도서전", year: 2023, item: "엽서", description: "엽서 세트 5,000장." },
    ],
    tags: ["1장부터", "셀프 업로드", "빠른 납기", "다양한 재질"],
  },
  {
    id: "14",
    name: "비즈하우스",
    location: "전국 (온라인)",
    description: "수백 가지 비즈니스 아이템 무료 디자인·제작. 스티커·포스터·에코백·판촉물 대량 인쇄 특화.",
    website: "https://www.bizhows.com",
    orderUrl: "https://www.bizhows.com/ko/",
    productTypes: ["스티커", "포스터", "에코백", "엽서"],
    minOrderQty: 10,
    unitPriceRange: { min: 200, max: 6000 },
    reorderCount: 33,
    references: [
      { studio: "Graphics Seoul", eventName: "현대카드 슈퍼콘서트", year: 2024, item: "포스터", description: "B1 포스터 1,000장." },
      { studio: "Ordinary People", eventName: "서울재즈페스티벌", year: 2023, item: "스티커", description: "판촉 스티커 5,000장." },
    ],
    tags: ["무료 디자인", "대량 특화", "빠른 배송", "다품목"],
  },
  {
    id: "15",
    name: "나눔인쇄",
    location: "서울",
    description: "24시간 자동견적 직영 인쇄소. 포스터·리플렛·엽서·책자 소량 인쇄 전문. 고품질·빠른 배송.",
    website: "https://nanumprinting.co.kr",
    orderUrl: "https://nanumprinting.co.kr/",
    productTypes: ["포스터", "엽서", "스티커"],
    minOrderQty: 10,
    unitPriceRange: { min: 300, max: 7000 },
    reorderCount: 24,
    references: [
      { studio: "Studio Paikku", eventName: "서울아트북페어", year: 2024, item: "포스터", description: "A2 포스터 300장." },
    ],
    tags: ["24시간 견적", "소량 전문", "직영 인쇄소"],
  },
  {
    id: "16",
    name: "로이프린팅",
    location: "서울 성북구 동소문로",
    description: "스티커·마스킹테이프·엽서·에코백 등 종합 굿즈·인쇄. 스티커 55원~, 소량 강점. 성북 직접 방문 가능.",
    website: "https://www.roiprinting.co.kr",
    orderUrl: "https://www.roiprinting.co.kr/shop",
    productTypes: ["스티커", "엽서", "포스터", "에코백"],
    minOrderQty: 1,
    unitPriceRange: { min: 55, max: 5000 },
    reorderCount: 17,
    references: [
      { studio: "Noname Press", eventName: "언리미티드 에디션", year: 2023, item: "스티커", description: "홀로그램 스티커 500장." },
      { studio: "Studio Maum", eventName: "서울아트북페어", year: 2022, item: "엽서", description: "엽서 200장." },
    ],
    tags: ["55원~", "성북 방문 가능", "마스킹테이프", "소량 강점"],
  },
  {
    id: "17",
    name: "프린팅팅",
    location: "인천 남동구 만수동",
    description: "인천 공장 직영 소량 디지털 인쇄. 스티커·엽서·포토카드·포스터·홀로그램 스티커 취급. 포토카드 16,500원~.",
    website: "https://printingting.com",
    orderUrl: "https://printingting.com",
    productTypes: ["스티커", "엽서", "포스터"],
    minOrderQty: 10,
    unitPriceRange: { min: 500, max: 5000 },
    reorderCount: 12,
    references: [
      { studio: "Studio Paikku", eventName: "부산국제영화제 (BIFF)", year: 2023, item: "스티커", description: "홀로그램 레터링 스티커 1,000장." },
    ],
    tags: ["공장 직영", "홀로그램", "포토카드", "인천 소재"],
  },
  {
    id: "18",
    name: "애드프린트",
    location: "전국 (온라인)",
    description: "고해상도 디지털 인쇄 전문. 포스터·스티커·전단 소량~대량 모두 가능. 온라인 견적 즉시 확인.",
    website: "https://adprint.co.kr",
    orderUrl: "https://adprint.co.kr/estimate?code=107",
    productTypes: ["포스터", "스티커", "엽서"],
    minOrderQty: 1,
    unitPriceRange: { min: 200, max: 8000 },
    reorderCount: 20,
    references: [
      { studio: "Graphics Seoul", eventName: "언리미티드 에디션", year: 2024, item: "포스터", description: "A1 포스터 200장." },
    ],
    tags: ["즉시 견적", "고해상도", "소량~대량", "전국 배송"],
  },
  {
    id: "19",
    name: "포스트링",
    location: "경기 남양주시 곡산읍",
    description: "엽서·명함·포스터·노트 소량 전문. 주문 후 1~2일 빠른 납기. 50장~, 일부 150장~ 주문 가능.",
    website: "https://www.postring.co.kr",
    orderUrl: "https://www.postring.co.kr",
    productTypes: ["엽서", "포스터", "스티커"],
    minOrderQty: 50,
    unitPriceRange: { min: 100, max: 3000 },
    reorderCount: 11,
    references: [
      { studio: "Noname Press", eventName: "서울아트북페어", year: 2024, item: "엽서", description: "아트 엽서 300장." },
    ],
    tags: ["1~2일 납기", "소량 전문", "엽서 특화"],
  },
  {
    id: "20",
    name: "디티피아",
    location: "서울 성동구 성수동",
    description: "성수동 DTPIA 빌딩 직영. 명함·스티커·포스터·책자 온라인 자동 견적. 떡메모지 2권~, 전단 10장~.",
    website: "https://dtpia.co.kr",
    orderUrl: "https://dtpia.co.kr",
    productTypes: ["스티커", "포스터", "엽서"],
    minOrderQty: 2,
    unitPriceRange: { min: 300, max: 6000 },
    reorderCount: 16,
    references: [
      { studio: "Studio Maum", eventName: "전주국제영화제", year: 2024, item: "엽서", description: "공식 행사 엽서 1,000장." },
    ],
    tags: ["성수동 직영", "자동 견적", "소량 가능"],
  },

  // ─── 금속배지 / 에나멜배지 / 핀배지 ──────────────────────
  {
    id: "21",
    name: "유앤아이",
    location: "서울",
    description: "30년 노하우의 금속배지 전문 제조사. 에나멜·에폭시·다이캐스팅 배지·메달·트로피. 품질 최상위.",
    website: "https://u-an-i.com",
    orderUrl: "https://u-an-i.com/_sub/order.html",
    productTypes: ["금속배지", "배지", "메달"],
    minOrderQty: 50,
    unitPriceRange: { min: 2000, max: 30000 },
    reorderCount: 22,
    references: [
      { studio: "Noname Press", eventName: "전주국제영화제", year: 2024, item: "금속배지", description: "에나멜 금속배지 300개, 금도금 마감." },
      { studio: "Ordinary People", eventName: "현대카드 슈퍼콘서트", year: 2023, item: "금속배지", description: "아티스트 콜라보 에나멜 배지 500개." },
    ],
    tags: ["30년 경력", "에나멜", "금도금", "최고급 마감"],
  },
  {
    id: "22",
    name: "Kevin's Room",
    location: "서울",
    description: "에나멜 금속배지·브로치 전문. 기본 3×3cm 이내 자유 형태 제작. 300개~, 3~5주 소요. 디자인 컨설팅 포함.",
    website: "https://www.kevinsroom.co.kr",
    orderUrl: "https://www.kevinsroom.co.kr/enamel-badge",
    productTypes: ["금속배지", "배지", "브로치"],
    minOrderQty: 300,
    unitPriceRange: { min: 3000, max: 20000 },
    reorderCount: 13,
    references: [
      { studio: "Graphics Seoul", eventName: "부산국제영화제 (BIFF)", year: 2024, item: "금속배지", description: "다이캐스팅 에나멜 배지 300개." },
    ],
    tags: ["에나멜 전문", "자유 형태", "디자인 컨설팅", "3~5주 제작"],
  },
  {
    id: "23",
    name: "만수금속",
    location: "서울 동대문구 용두동",
    description: "국내 금속 프레스 가공 전문. 메달·배지·키링·코인·문진 제작. 동대문구 자체 공장 운영.",
    website: "http://mansumetal.com",
    orderUrl: "http://mansumetal.com",
    productTypes: ["금속배지", "배지", "아크릴 키링"],
    minOrderQty: 100,
    unitPriceRange: { min: 1500, max: 25000 },
    reorderCount: 10,
    references: [
      { studio: "Studio Maum", eventName: "서울국제도서전", year: 2023, item: "금속배지", description: "에폭시 배지 200개." },
    ],
    tags: ["자체 공장", "금속 프레스", "동대문 소재", "메달 제작"],
  },
  {
    id: "24",
    name: "크로서블스",
    location: "서울 금천구",
    description: "배지·패치·메달·아크릴 제품 종합. 아크릴 MOQ 50~100개, 고무 50~300개, 메달 10개~. 웰컴키트·기업 패키지 강점.",
    website: "https://crossables.com",
    orderUrl: "https://crossables.com",
    productTypes: ["배지", "핀배지", "금속배지", "아크릴 키링"],
    minOrderQty: 10,
    unitPriceRange: { min: 800, max: 15000 },
    reorderCount: 9,
    references: [
      { studio: "Studio Paikku", eventName: "인디 뮤직 페스티벌", year: 2024, item: "핀배지", description: "아티스트 핀배지 150개." },
    ],
    tags: ["낮은 MOQ", "종합 굿즈", "웰컴키트", "기업 패키지"],
  },
  {
    id: "25",
    name: "루아샵",
    location: "경기 양주시",
    description: "핀버튼·배지·아크릴 키링 1개부터 소량 주문. 평균 2~3일 제작. 핀버튼 140원~, 아크릴 키링 650원~. 고객센터 1544-9619.",
    website: "https://www.ruashop.co.kr",
    orderUrl: "https://www.ruashop.co.kr/",
    productTypes: ["핀배지", "배지", "아크릴 키링"],
    minOrderQty: 1,
    unitPriceRange: { min: 140, max: 3000 },
    reorderCount: 38,
    references: [
      { studio: "Noname Press", eventName: "전주국제영화제", year: 2024, item: "핀배지", description: "58mm 핀버튼 500개." },
      { studio: "Studio Paikku", eventName: "부산국제영화제 (BIFF)", year: 2023, item: "아크릴 키링", description: "자유형 아크릴 키링 300개." },
      { studio: "Graphics Seoul", eventName: "현대카드 슈퍼콘서트", year: 2024, item: "핀배지", description: "핀버튼 1,000개." },
    ],
    tags: ["1개부터", "2~3일 제작", "140원~", "다양한 사이즈"],
  },

  // ─── 아크릴 키링 ───────────────────────────────────────────
  {
    id: "26",
    name: "올댓프린팅",
    location: "경기 고양시",
    description: "창작자 타겟 아크릴·우드·랜야드 전문 굿즈 제작. 소량 1개~, 렌티큘러 아크릴도 취급. B2B 기업 납품 가능.",
    website: "https://allthatprinting.co.kr",
    orderUrl: "https://allthatprinting.co.kr/",
    productTypes: ["아크릴 키링", "랜야드", "렌티큘러 엽서"],
    minOrderQty: 1,
    unitPriceRange: { min: 500, max: 6000 },
    reorderCount: 29,
    references: [
      { studio: "Ordinary People", eventName: "서울아트북페어", year: 2024, item: "아크릴 키링", description: "자유형 아크릴 키링 200개." },
      { studio: "Graphics Seoul", eventName: "부산국제영화제 (BIFF)", year: 2023, item: "랜야드", description: "행사용 랜야드 300개." },
    ],
    tags: ["1개부터", "렌티큘러 취급", "창작자 특화", "B2B 가능"],
  },
  {
    id: "27",
    name: "한올디앤피",
    location: "경기 고양시 일산동구 백석동",
    description: "UV인쇄+레이저 커팅 자체 공장. 아크릴 키링·홀로그램·카드·스탠드 소량 30개~. 일산테크노타운 직영.",
    website: "https://hanalldnp.co.kr",
    orderUrl: "https://hanalldnp.co.kr/category/아크릴/24/",
    productTypes: ["아크릴 키링"],
    minOrderQty: 30,
    unitPriceRange: { min: 700, max: 5000 },
    reorderCount: 11,
    references: [
      { studio: "Studio Maum", eventName: "서울국제도서전", year: 2024, item: "아크릴 키링", description: "홀로그램 아크릴 키링 100개." },
    ],
    tags: ["자체 공장", "UV인쇄", "홀로그램", "일산 소재"],
  },
  {
    id: "28",
    name: "굿즈드랍",
    location: "경기 안산시 상록구",
    description: "(주)리틀웨이브 운영. 아크릴 키링 500원~, 포토카드 2,500원~. OEM 가능. B2B 다품종 아크릴 강점.",
    website: "https://goodsdrop.co.kr",
    orderUrl: "https://goodsdrop.co.kr/product/keyring/",
    productTypes: ["아크릴 키링", "엽서"],
    minOrderQty: 10,
    unitPriceRange: { min: 500, max: 4000 },
    reorderCount: 14,
    references: [
      { studio: "Ordinary People", eventName: "카카오프렌즈 팝업스토어", year: 2024, item: "아크릴 키링", description: "캐릭터 아크릴 키링 1,000개, OEM." },
    ],
    tags: ["500원~", "OEM 가능", "B2B", "안산 공장"],
  },
  {
    id: "29",
    name: "아이텐션",
    location: "경기 김포시 양촌읍",
    description: "(주)온앤율 운영. 아크릴 키링 500원~, 등신대 2,550원~. 김포 공장 직영, 빠른 납기.",
    website: "https://itension.co.kr",
    orderUrl: "https://itension.co.kr",
    productTypes: ["아크릴 키링"],
    minOrderQty: 1,
    unitPriceRange: { min: 500, max: 5000 },
    reorderCount: 16,
    references: [
      { studio: "Studio Paikku", eventName: "인디 뮤직 페스티벌", year: 2024, item: "아크릴 키링", description: "아티스트 아크릴 키링 300개." },
    ],
    tags: ["공장 직영", "빠른 납기", "김포 소재", "다양한 굿즈"],
  },
  {
    id: "30",
    name: "피노",
    location: "충북 청주 (서울 성수동 사무소)",
    description: "청주 공장 100% 자체 생산. 아크릴 100원~. 원자재~조립 일괄. 양산 1,000개~, 샘플 10개 이하 가능.",
    website: "https://pinot.co.kr",
    orderUrl: "https://pinot.co.kr",
    productTypes: ["아크릴 키링"],
    minOrderQty: 10,
    unitPriceRange: { min: 100, max: 3000 },
    reorderCount: 9,
    references: [
      { studio: "Noname Press", eventName: "전주국제영화제", year: 2023, item: "아크릴 키링", description: "배면+라미 아크릴 키링 500개." },
    ],
    tags: ["100원~", "청주 공장", "샘플 가능", "라미 인쇄"],
  },
  {
    id: "31",
    name: "코알라디자인",
    location: "서울 성북구 정릉",
    description: "UV프린팅+레이저 커팅. 아크릴 키링 700원~, 마그넷 1,100원~. 키링·마그넷 10개~/도안. 샘플 1개 2,500원.",
    website: "https://koaladesign.co.kr",
    orderUrl: "https://koaladesign.co.kr/26",
    productTypes: ["아크릴 키링"],
    minOrderQty: 10,
    unitPriceRange: { min: 700, max: 4000 },
    reorderCount: 13,
    references: [
      { studio: "Studio Maum", eventName: "서울재즈페스티벌", year: 2023, item: "아크릴 키링", description: "아티스트 마그넷+키링 세트 200개." },
    ],
    tags: ["10개~", "샘플 1개 가능", "UV프린팅", "정릉 소재"],
  },
  {
    id: "32",
    name: "케이스밤",
    location: "경기 부천시 춘의테크노파크",
    description: "부천 공장 직영. 아크릴 키링 500원~, 미니등신대 2,000원~. 렌티큘러 아크릴·띠부씰 스티커 취급. 1개 소량 가능.",
    website: "https://casebomb.co.kr",
    orderUrl: "https://casebomb.co.kr",
    productTypes: ["아크릴 키링", "렌티큘러 엽서", "스티커"],
    minOrderQty: 1,
    unitPriceRange: { min: 450, max: 5000 },
    reorderCount: 17,
    references: [
      { studio: "Ordinary People", eventName: "부산국제영화제 (BIFF)", year: 2024, item: "아크릴 키링", description: "렌티큘러 아크릴 키링 200개." },
    ],
    tags: ["1개부터", "렌티큘러 아크릴", "부천 공장", "띠부씰"],
  },
  {
    id: "33",
    name: "먼데이팩토리",
    location: "경기 성남시 분당구",
    description: "퍼스널브랜딩·굿즈·웰컴키트·판촉물 종합. 배지·패키지·금속배지 기획제작. 해외 소싱 공장 발굴 역량 보유.",
    website: "https://mondayfactory.co.kr",
    orderUrl: "https://mondayfactory.co.kr/",
    productTypes: ["배지", "금속배지", "차음료 패키지", "아크릴 키링"],
    minOrderQty: 50,
    unitPriceRange: { min: 500, max: 30000 },
    reorderCount: 21,
    references: [
      { studio: "Graphics Seoul", eventName: "현대카드 뮤직 라이브러리", year: 2024, item: "금속배지", description: "아티스트 에나멜 배지 세트 200개." },
      { studio: "Ordinary People", eventName: "서울재즈페스티벌", year: 2023, item: "차음료 패키지", description: "행사 기념 블렌딩 티 패키지 100세트." },
    ],
    tags: ["해외 소싱", "웰컴키트", "기획 제작", "분당 소재"],
  },
  {
    id: "34",
    name: "오즈의 제작소",
    location: "서울",
    description: "1:1 전담 PM이 예산·납기·컨셉에 맞는 굿즈 추천~배송까지 원스톱 진행. 아크릴·배지·스티커 등 다품종.",
    website: "https://ozjejakso.com",
    orderUrl: "https://ozjejakso.com/product",
    productTypes: ["아크릴 키링", "배지", "스티커"],
    minOrderQty: 50,
    unitPriceRange: { min: 500, max: 15000 },
    reorderCount: 18,
    references: [
      { studio: "Noname Press", eventName: "서울아트북페어", year: 2023, item: "아크릴 키링", description: "아트 키링+포장 패키지 100세트." },
    ],
    tags: ["1:1 PM", "원스톱", "포장 포함", "다품종"],
  },
  {
    id: "35",
    name: "휴앤고",
    location: "전국 (온라인)",
    description: "오늘 주문 오늘 발송. 무료 샘플 제공. 아크릴 키링·스탠드·마우스패드·쿠션 1개부터 소량 제작.",
    website: "https://hueandgo.com",
    orderUrl: "https://hueandgo.com",
    productTypes: ["아크릴 키링"],
    minOrderQty: 1,
    unitPriceRange: { min: 500, max: 8000 },
    reorderCount: 23,
    references: [
      { studio: "Studio Paikku", eventName: "인디 뮤직 페스티벌", year: 2023, item: "아크릴 키링", description: "공연 기념 아크릴 키링 100개." },
    ],
    tags: ["당일 발송", "무료 샘플", "1개부터", "다양한 굿즈"],
  },

  // ─── 렌티큘러 엽서 ─────────────────────────────────────────
  {
    id: "36",
    name: "렌티큘러코리아",
    location: "서울/경기",
    description: "렌티큘러 인쇄 전문 제조사. 엽서·포토카드·포스터·키링 등 렌티큘러 전 품목. 대량·소량 모두 대응.",
    website: "http://lenticularkorea.com",
    orderUrl: "http://lenticularkorea.com",
    productTypes: ["렌티큘러 엽서"],
    minOrderQty: 50,
    unitPriceRange: { min: 500, max: 5000 },
    reorderCount: 12,
    references: [
      { studio: "Graphics Seoul", eventName: "부산국제영화제 (BIFF)", year: 2023, item: "렌티큘러 엽서", description: "변환 렌티 포토카드 500장." },
    ],
    tags: ["렌티큘러 전문", "대소량 대응", "전 품목"],
  },
  {
    id: "37",
    name: "쓰리디자인",
    location: "경기 고양시 덕양구",
    description: "렌티큘러 변환 엽서·포토카드 전문. 100장~, OPP 봉투 포함. 앞면 4도+뒷면 1도 인쇄. 평균 5~10일 납기.",
    website: "https://3designart.co.kr",
    orderUrl: "https://3designart.co.kr/product/렌티큘러-변-엽서-양면인쇄-100장-주문제작/84/",
    productTypes: ["렌티큘러 엽서"],
    minOrderQty: 100,
    unitPriceRange: { min: 400, max: 3000 },
    reorderCount: 15,
    references: [
      { studio: "Noname Press", eventName: "전주국제영화제", year: 2024, item: "렌티큘러 엽서", description: "렌티 변환 엽서 300장, OPP 포장 포함." },
      { studio: "Studio Paikku", eventName: "서울아트북페어", year: 2023, item: "렌티큘러 엽서", description: "작가 포토카드 200장." },
    ],
    tags: ["OPP 봉투 포함", "100장~", "5~10일 납기", "양면 인쇄"],
  },
  {
    id: "38",
    name: "아르떼포토",
    location: "경기 고양시 일산동구 백석동",
    description: "렌티큘러 엽서·포토카드 1매 단위 출력 가능. 렌티+일반 굿즈 병행. 일산테크노타운 공장 직영.",
    website: "https://artefoto.co.kr",
    orderUrl: "https://artefoto.co.kr/category/렌티엽서카드/637/",
    productTypes: ["렌티큘러 엽서"],
    minOrderQty: 1,
    unitPriceRange: { min: 800, max: 6000 },
    reorderCount: 8,
    references: [
      { studio: "Studio Maum", eventName: "서울국제도서전", year: 2024, item: "렌티큘러 엽서", description: "작가 한정 렌티 포토카드 150장." },
    ],
    tags: ["1매부터", "공장 직영", "일산 소재", "일반 굿즈 병행"],
  },

  // ─── 텀블러 / 머그컵 ───────────────────────────────────────
  {
    id: "39",
    name: "머그하우스",
    location: "경북 청도군 풍각면",
    description: "2004년 설립. 승화 전사·수전사 인쇄 전문. 머그컵 3,100원~, 텀블러·유리컵도 취급. 카페 굿즈 납품 다수.",
    website: "https://mughouse.co.kr",
    orderUrl: "https://mughouse.co.kr/",
    productTypes: ["텀블러", "머그컵"],
    minOrderQty: 30,
    unitPriceRange: { min: 3100, max: 12000 },
    reorderCount: 19,
    references: [
      { studio: "Graphics Seoul", eventName: "현대카드 슈퍼콘서트", year: 2024, item: "텀블러", description: "풀컬러 승화 텀블러 500개." },
    ],
    tags: ["2004년 설립", "승화 전사", "수전사", "청도 공장"],
  },
  {
    id: "40",
    name: "머그나라",
    location: "경북 칠곡군 석적읍",
    description: "공장 직영. 포토머그 3,500원~, 변색머그 2,250원~, 대량 1,640원~. 1개 소량~1,000개+ 대량 모두 경쟁력.",
    website: "https://mugnara.co.kr",
    orderUrl: "https://mugnara.co.kr/",
    productTypes: ["텀블러", "머그컵"],
    minOrderQty: 1,
    unitPriceRange: { min: 1640, max: 12000 },
    reorderCount: 14,
    references: [
      { studio: "Studio Paikku", eventName: "서울국제도서전", year: 2024, item: "머그컵", description: "변색머그 200개, 로고 인쇄." },
    ],
    tags: ["공장 직영", "변색머그", "1개~대량", "가성비"],
  },
  {
    id: "41",
    name: "투데이머그",
    location: "서울 강남구 논현동 (전국 6개 지점)",
    description: "부산·대구·대전·광주·제주 포함 전국 6지점. 머그 2,050원~, 텀블러 최대 20,300원. 소량도 당일 가능.",
    website: "https://todaygift.co.kr",
    orderUrl: "https://todaygift.co.kr/mug/",
    productTypes: ["텀블러", "머그컵"],
    minOrderQty: 1,
    unitPriceRange: { min: 2050, max: 20300 },
    reorderCount: 10,
    references: [
      { studio: "Ordinary People", eventName: "현대카드 뮤직 라이브러리", year: 2023, item: "텀블러", description: "포토 텀블러 100개." },
    ],
    tags: ["전국 6지점", "당일 가능", "2,050원~", "방문 주문"],
  },

  // ─── 모자 ──────────────────────────────────────────────────
  {
    id: "42",
    name: "모자팩토리",
    location: "서울 중구 신당동",
    description: "볼캡·스냅백·캠프캡·버킷햇·바이저 자수·인쇄 맞춤 제작. 1개부터 대량까지. 전화 070-5089-0140.",
    website: "https://mojafactory.com",
    orderUrl: "https://mojafactory.com/category/맞춤제작/107/",
    productTypes: ["모자", "볼캡"],
    minOrderQty: 1,
    unitPriceRange: { min: 8000, max: 40000 },
    reorderCount: 14,
    references: [
      { studio: "Ordinary People", eventName: "부산국제영화제 (BIFF)", year: 2024, item: "버킷햇", description: "자수 버킷햇 300개." },
      { studio: "Studio Maum", eventName: "서울재즈페스티벌", year: 2023, item: "볼캡", description: "자수 볼캡 500개." },
    ],
    tags: ["자수 전문", "1개부터", "신당동 방문", "다양한 모자"],
  },
  {
    id: "43",
    name: "스마트모자",
    location: "경기 안양시 만안구 안양동",
    description: "(스마트에프앤씨) 국내 공장 직영. 기능성 볼캡·러닝캡·버킷햇. 기능성·골프·테니스 모자 특화.",
    website: "https://www.smartmoja.com",
    orderUrl: "https://www.smartmoja.com",
    productTypes: ["모자", "볼캡"],
    minOrderQty: 10,
    unitPriceRange: { min: 10000, max: 40000 },
    reorderCount: 7,
    references: [
      { studio: "Graphics Seoul", eventName: "현대카드 슈퍼콘서트", year: 2024, item: "볼캡", description: "기능성 볼캡 200개." },
    ],
    tags: ["국내 공장", "기능성 모자", "골프·테니스", "안양 소재"],
  },

  // ─── 수첩 / 노트 ───────────────────────────────────────────
  {
    id: "44",
    name: "드림산업(주)",
    location: "서울 중구",
    description: "수첩·노트·다이어리 전문 제조. 양장·링·밴드 제본 다양. 기업 단체 납품 다수. 고객센터 02-2263-8781.",
    website: "https://dimemo.co.kr",
    orderUrl: "https://dimemo.co.kr/",
    productTypes: ["노트"],
    minOrderQty: 50,
    unitPriceRange: { min: 3000, max: 22000 },
    reorderCount: 12,
    references: [
      { studio: "Noname Press", eventName: "서울아트북페어", year: 2024, item: "노트", description: "A5 양장 노트 300권, 리넨 커버." },
      { studio: "Graphics Seoul", eventName: "서울국제도서전", year: 2023, item: "노트", description: "B6 링 수첩 500권." },
    ],
    tags: ["양장 제본", "링 제본", "기업 납품", "서울 중구"],
  },

  // ─── 랜야드 / 비표끈 ──────────────────────────────────────
  {
    id: "45",
    name: "드림월드",
    location: "서울",
    description: "랜야드·비표끈·목걸이줄 전문 판촉물 업체. 행사용 비표끈 소량~대량 제작. 다양한 클립·버클 옵션.",
    website: "https://dworldinc.co.kr",
    orderUrl: "https://dworldinc.co.kr/product/디지털-원단프린팅dtp/212/",
    productTypes: ["랜야드"],
    minOrderQty: 50,
    unitPriceRange: { min: 800, max: 6000 },
    reorderCount: 16,
    references: [
      { studio: "Noname Press", eventName: "전주국제영화제", year: 2023, item: "랜야드", description: "행사 스태프 비표끈 200개." },
      { studio: "Ordinary People", eventName: "현대카드 슈퍼콘서트", year: 2023, item: "랜야드", description: "공연 MD 목걸이 스트랩 500개." },
    ],
    tags: ["랜야드 전문", "비표끈", "다양한 버클", "행사용"],
  },

  // ─── 반다나 / 손수건 ──────────────────────────────────────
  {
    id: "46",
    name: "이든스랩",
    location: "인천 부평구",
    description: "손수건·반다나 패브릭 전사 전문. 실크인쇄·디지털인쇄 선택 가능. MOQ 100개, 3주 이내 제작.",
    website: "https://eadenslab.com",
    orderUrl: "https://eadenslab.com/bandana",
    productTypes: ["반다나", "쉬폰 천 인쇄"],
    minOrderQty: 100,
    unitPriceRange: { min: 2000, max: 10000 },
    reorderCount: 9,
    references: [
      { studio: "Studio Maum", eventName: "서울재즈페스티벌", year: 2023, item: "반다나", description: "면 반다나 200개, 디지털 전사 인쇄." },
    ],
    tags: ["MOQ 100개", "실크+디지털", "3주 제작", "인천 소재"],
  },
  {
    id: "47",
    name: "JJB LAB",
    location: "서울",
    description: "스카프·반다나·손수건·패브릭 포스터·넥타이 텍스타일 제품 전 품목 맞춤 제작. 디자이너·브랜드 협업 특화.",
    website: "https://jjb-lab.com",
    orderUrl: "https://jjb-lab.com/custom-textile-products",
    productTypes: ["반다나", "쉬폰 천 인쇄"],
    minOrderQty: 50,
    unitPriceRange: { min: 3000, max: 20000 },
    reorderCount: 11,
    references: [
      { studio: "Graphics Seoul", eventName: "현대카드 뮤직 라이브러리", year: 2024, item: "반다나", description: "아티스트 콜라보 반다나 150개." },
      { studio: "Noname Press", eventName: "서울아트북페어", year: 2023, item: "스카프", description: "작가 아트 스카프 100개." },
    ],
    tags: ["텍스타일 전문", "스카프·반다나", "디자이너 협업", "고급 소재"],
  },

  // ─── 쉬폰 천 인쇄 / 패브릭 프린팅 ───────────────────────
  {
    id: "48",
    name: "리얼패브릭",
    location: "서울",
    description: "디지털 원단 프린팅(DTP) 전문. 쉬폰·폴리·면 등 소량~대량 원단 인쇄. 프린트리 서비스 운영.",
    website: "https://realfabric.net",
    orderUrl: "https://realfabric.net/",
    productTypes: ["쉬폰 천 인쇄", "반다나"],
    minOrderQty: 1,
    unitPriceRange: { min: 5000, max: 50000 },
    reorderCount: 13,
    references: [
      { studio: "Studio Maum", eventName: "전주국제영화제", year: 2024, item: "쉬폰 천 인쇄", description: "쉬폰 플래그 배너 50장." },
      { studio: "Ordinary People", eventName: "언리미티드 에디션", year: 2023, item: "쉬폰 천 인쇄", description: "아티스트 아트 패브릭 80장." },
    ],
    tags: ["DTP 전문", "쉬폰 원단", "소량 가능", "다양한 원단"],
  },
  {
    id: "49",
    name: "패브릭팜",
    location: "대구 서구 (서울 종로구 사무소)",
    description: "독립 디자이너 원단 특화. 패브릭 스티커 3,000원~, 블랭킷·손수건·맞춤 디자인 원단. 대안텍스타일 계열.",
    website: "https://www.fabricfarm.co.kr",
    orderUrl: "https://www.fabricfarm.co.kr/mall/goods/dtp",
    productTypes: ["쉬폰 천 인쇄", "반다나"],
    minOrderQty: 1,
    unitPriceRange: { min: 3000, max: 40000 },
    reorderCount: 7,
    references: [
      { studio: "Graphics Seoul", eventName: "서울아트북페어", year: 2023, item: "쉬폰 천 인쇄", description: "작가 패브릭 포스터 30장." },
    ],
    tags: ["디자이너 특화", "패브릭 스티커", "소량 가능", "대구+종로"],
  },

  // ─── 양말 ──────────────────────────────────────────────────
  {
    id: "50",
    name: "삭스킹",
    location: "경기 하남시 미사 (공장: 경기 광주)",
    description: "3D 양말 커스터마이징 플랫폼. OEM/ODM 전문. 발목·중목·장목·무릎양말 전 종류. 헤어밴드·손목밴드 병행.",
    website: "https://www.socksking.com",
    orderUrl: "https://www.socksking.com",
    productTypes: ["양말"],
    minOrderQty: 100,
    unitPriceRange: { min: 2500, max: 10000 },
    reorderCount: 8,
    references: [
      { studio: "Studio Paikku", eventName: "인디 뮤직 페스티벌", year: 2023, item: "양말", description: "자카드 로고 양말 300켤레." },
      { studio: "Ordinary People", eventName: "카카오프렌즈 팝업스토어", year: 2024, item: "양말", description: "캐릭터 승화 양말 1,000켤레." },
    ],
    tags: ["OEM/ODM", "3D 커스텀", "전 종류 취급", "하남+광주"],
  },

  // ─── 차음료 패키지 ─────────────────────────────────────────
  {
    id: "51",
    name: "박스컴퍼니",
    location: "경기",
    description: "소량 100개부터 커스텀 패키지 박스 제작. 차음료·식품 포장 박스, 선물세트 패키지 1:1 컨설팅 제공.",
    website: "https://boxcompany.co.kr",
    orderUrl: "https://boxcompany.co.kr/",
    productTypes: ["차음료 패키지"],
    minOrderQty: 100,
    unitPriceRange: { min: 500, max: 8000 },
    reorderCount: 10,
    references: [
      { studio: "Ordinary People", eventName: "서울아트북페어", year: 2024, item: "차음료 패키지", description: "아티스트 블렌딩 티 선물세트 박스 100개." },
      { studio: "Studio Maum", eventName: "서울재즈페스티벌", year: 2023, item: "차음료 패키지", description: "행사 기념 티백 패키지 200세트." },
    ],
    tags: ["100개~", "1:1 컨설팅", "식품 포장", "선물세트"],
  },

  // ─── 종합 굿즈 플랫폼 ─────────────────────────────────────
  {
    id: "52",
    name: "비즈팩토리",
    location: "경기",
    description: "전단·스티커·포스터·명함·현수막·텀블러·수첩 소량~대량 종합 인쇄. 온라인 주문 즉시 자동 견적.",
    website: "https://www.bizfactory.co.kr",
    orderUrl: "https://www.bizfactory.co.kr/",
    productTypes: ["스티커", "포스터", "텀블러", "노트"],
    minOrderQty: 1,
    unitPriceRange: { min: 200, max: 15000 },
    reorderCount: 19,
    references: [
      { studio: "Graphics Seoul", eventName: "언리미티드 에디션", year: 2023, item: "포스터", description: "A1 포스터 300장." },
      { studio: "Studio Maum", eventName: "서울국제도서전", year: 2022, item: "스티커", description: "판촉 스티커 5,000장." },
    ],
    tags: ["종합 인쇄", "자동 견적", "다품목", "소량~대량"],
  },
  {
    id: "53",
    name: "인쇄랑",
    location: "경기 안양시 동안구 호계동",
    description: "소량 인쇄 전문. 스티커 55원~, 전단 62원~, 명함 60원~. 상품택·케이크픽 등 소품 전문. 단가 최저가 경쟁력.",
    website: "https://insaerang.co.kr",
    orderUrl: "https://insaerang.co.kr",
    productTypes: ["스티커", "엽서"],
    minOrderQty: 1,
    unitPriceRange: { min: 55, max: 3000 },
    reorderCount: 14,
    references: [
      { studio: "Studio Paikku", eventName: "서울아트북페어", year: 2024, item: "스티커", description: "포장용 씰 스티커 1,000장." },
    ],
    tags: ["55원~", "최저가", "소량 전문", "안양 소재"],
  },
  {
    id: "54",
    name: "인터프로프린트",
    location: "경기 의정부시 (출고: 서울 충무로)",
    description: "인디고 디지털+오프셋 혼합 인쇄. 스티커·엽서·포스터·명함·배너 1개~. 명함 2,900원~, 포스터 3,000원~.",
    website: "https://www.interproprint.com",
    orderUrl: "https://www.interproprint.com",
    productTypes: ["스티커", "포스터", "엽서"],
    minOrderQty: 1,
    unitPriceRange: { min: 200, max: 8000 },
    reorderCount: 16,
    references: [
      { studio: "Noname Press", eventName: "전주국제영화제", year: 2023, item: "포스터", description: "A3 공식 포스터 2,000장 오프셋." },
    ],
    tags: ["인디고+오프셋", "1개~", "충무로 출고", "자동 견적"],
  },
  {
    id: "55",
    name: "위드굿즈",
    location: "서울 은평구 서울혁신파크",
    description: "아트굿즈 마켓플레이스. 텀블러·유리컵·코스터·패브릭 가방·타이포굿즈 온디맨드 생산. 개별 포장 무료.",
    website: "https://withgoods.net",
    orderUrl: "https://withgoods.net/business",
    productTypes: ["텀블러", "에코백", "스티커"],
    minOrderQty: 1,
    unitPriceRange: { min: 3000, max: 20000 },
    reorderCount: 6,
    references: [
      { studio: "Graphics Seoul", eventName: "서울아트북페어", year: 2024, item: "텀블러", description: "작가 아트 텀블러 50개, 개별 포장." },
    ],
    tags: ["온디맨드", "개별 포장 무료", "아트굿즈", "은평 소재"],
  },
];
